#ifndef NETWORK_CLIENT_STATUS_H
#define NETWORK_CLIENT_STATUS_H

enum network_client_status {
    NETWORK_CLIENT_NONE = 0,
    NETWORK_CLIENT_CONNECTED = 1,
    NETWORK_CLIENT_LIVE = 2,
    NETWORK_CLIENT_MANAGEMENT = 3,
};

#endif // NETWORK_CLIENT_STATUS_H